/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import javax.management.MBeanServerConnection;

public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() throws IOException {
        assertEquals(MBeanServerConnection.class, JmxBossPoll.getJmxConnection(null, null, null, 0));
    }*/
}
